name: prefect-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      # Prefect core + AWS block (保持版本兼容性)
      - prefect==2.14.9
      - prefect-aws==0.2.3
      - pydantic==1.10.13
      - griffe==0.49.0

      # ML & Data stack
      - mlflow==2.3.1
      - xgboost==1.7.5
      - scikit-learn==1.3.2
      - pandas==2.1.3
      - seaborn==0.12.2
      - fastparquet==2023.4.0
      - orjson>=3.9.7

      # Dev tools / optimization
      - black==23.3.0
      - hyperopt==0.2.7

      # Prefect Server Notification dependency
      - apprise[full]==1.2.1

      # Async compatibility with Prefect
      - anyio>=3.6.2,<4.0
